### ISSUE TITLE
Command to see who is holding up the game

### ISSUE THREAD

**Issue by d0tcc** [d0tcc/Secret-Blue#10]
Implementation of @egenender 's solution for this problem: [see suggestion 1](https://github.com/julianschritt/secreth_telegrambot/pull/2#issuecomment-328098925)

**Comment by leviatas** [comment]
I suppose the log method saves the time, is easy to navigate the log?

Otherwise we will have to made atributes to save when the voting started and a list of who voted.

**Comment by leviatas** [comment]
I was watching the code, the log saves in a text file and it's a log of every game.

We should made a list with the votes and then call it.

We can do a list with many list so we can call the history of votes, If we want, in the future.

**Comment by leviatas** [comment]
I'm working on the command. 

@julianschritt You were wondering about auto deploying new changes. I found that Haroku has autodeploy from github. Is very usefull when testing.

**Comment by leviatas** [comment]
Ok, I added 3 pull request. When I made the first one I supposed that I could join them, you can't XD

#17 #18 #19

**Comment by d0tcc** [comment]
Great, thank you! Did you test it?

**Comment by leviatas** [comment]
I tested in a fork I made of your code. You can try to put it in the test bot if you want first to see if it has any code problem

**Comment by d0tcc** [comment]
ok, it's in the testbot now

**Comment by julianschritt** [comment]
@leviatas The new commands are not working. "global name 'datetime' is not defined". I guess you just have to import datetime ...
please test new functionalities on your own instance of the bot (you can create a new bot with the botfather and run it locally for manual tests ... Or maybe someone wants to write automated tests #4?! 😁 😁 😁 )

**Comment by d0tcc** [comment]
reopened it because I didn't see #21

**Comment by julianschritt** [comment]
... and now I have to reopen it anyway ...

**Comment by d0tcc** [comment]
... and now I have to reopen it anyway ... 😄 
@leviatas
/calltovote does not work: "global name 'ParseMode' is not defined"
Please test your adaptions on your own instance of the bot before creating a pull request (you can create a new bot with the botfather and run it locally for tests ... or maybe someone wants to write automated tests??!? 😁 😁 😁  #4 )

**Comment by leviatas** [comment]
I made some test and it was working, the thing is that I made a lot of changes in my fork (Because yo make it work in Haroku I had to change the logging, add some files, etc..)  and move the changes for the command only, I only forgot the import of libraries datetime and parse mode in the commands.

**Comment by d0tcc** [comment]
I know you suggested Heroku in the past but I host the testbot on a rented server now and implemented automated updates myself and I plan to transfer the main bot to the server as well soon.
thanks for the new pull request anyway :)

**Comment by leviatas** [comment]
No problem :)

The thing with Heroku is that is free, and I didn't knew if you wanted to pay a host for something that is a hobbie.
