### ISSUE TITLE
Testing new features with the @sechit_testbot

### ISSUE THREAD

**Issue by d0tcc** [d0tcc/Secret-Blue#11]
Hi @egenender, @Karho, @leviatas, @HQ063!

As long as we don't have automated tests I would like to test new features with a [separate bot](http://t.me/sechit_testbot)

It is running the latest version with all the new changes, the complete restructured architecture and on a new server.
If it is possible for you, please play a few games with it and report if there are any bugs in it. You may want to remove the old bot from your group since there will be a conflict concerning the commands.
After a few successful games I will update the main bot to this version as well.

I plan on testing new features this way as long as there is a better way (i.e. automated tests).

Thank you so much for your support!

**Comment by leviatas** [comment]
Can You add the commands with the bot father so we can access Them easily?

**Comment by d0tcc** [comment]
Done!

**Comment by leviatas** [comment]
We already tested the features in a test bot. They work well.

**Comment by d0tcc** [comment]
I will transfer the main bot to the new server in about half an hour. The testbot will be shut off for now ...
