### ISSUE TITLE
Using sample instead of shuffle

### ISSUE THREAD

**Issue by egenender** [d0tcc/Secret-Blue#6]
Random.sample is beign used in places where the actual functionality is to shuffle.

**Comment by d0tcc** [comment]
[random.sample(list, k)](https://docs.python.org/2/library/random.html#random.sample) returns a shuffled k length list picked out of the list. by choosing k as len(list) this expression simply shuffles the list.

**Comment by leviatas** [comment]
We say that in two games in a row happened the 3L situation ~ 5% and it was odd for us.
