### ISSUE TITLE
Shuffling remaining policies

### ISSUE THREAD

**Issue by egenender** [d0tcc/Secret-Blue#8]
As per rules: after Anarchy or after a Legislative Session, if there are fewer than 3 policies in the policy deck, it has to be re-shuffled (right after anarchy or legislative session).
Usually, if no anarchy is applied, in the first round the deck goes from 5 policies to 2 policies. At this moment, the cards should be reshuffled (but they aren't). Instead, the bot wait for the next legislative session, shuffling them before handing out the cards to the president.
Same rule is broken if Anarchy applies a policy and results in fewer than 3 policies in the deck.

**Comment by leviatas** [comment]
I made a pull request about this.

https://github.com/julianschritt/secreth_telegrambot/pull/9

**Comment by d0tcc** [comment]
thank you!

**Comment by leviatas** [comment]
To you, for making this awesome bot.

Julian, when you see it possible update the bot? So we can test the changes.
